services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: waterpump-postgres
    environment:
      POSTGRES_DB: waterpump
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - waterpump-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: waterpump-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - waterpump-network
    restart: unless-stopped

  # InfluxDB Time Series Database
  influxdb:
    image: influxdb:2.7-alpine
    container_name: waterpump-influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: waterpump-org
      DOCKER_INFLUXDB_INIT_BUCKET: waterpump
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: your-influxdb-token
    ports:
      - "8087:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - waterpump-network
    restart: unless-stopped

  # Nest.js Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    container_name: waterpump-api
    environment:
      NODE_ENV: development
      PORT: 3000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: waterpump
      REDIS_HOST: redis
      REDIS_PORT: 6379
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: your-influxdb-token
      INFLUXDB_ORG: waterpump-org
      INFLUXDB_BUCKET: waterpump
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - redis
      - influxdb
    networks:
      - waterpump-network
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules

volumes:
  postgres_data:
  redis_data:
  influxdb_data:

networks:
  waterpump-network:
    driver: bridge 