services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: waterpump-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-waterpump}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${POSTGRES_PORT:-5436}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - waterpump-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: waterpump-redis
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    networks:
      - waterpump-network
    restart: unless-stopped

  # InfluxDB 3.3 Core Time Series Database
  influxdb:
    image: influxdb:3.3-core
    container_name: waterpump-influxdb
    command: >
      influxdb3
      serve
      --node-id=node0
      --object-store=file
      --data-dir=/var/lib/influxdb3/data
      --plugin-dir=/var/lib/influxdb3/plugins
      --without-auth
      --max-memory=4GB
      --max-query-memory=1GB
      --wal-max-concurrent-reads=4
      --wal-max-batch-size=1000
      --wal-sync-interval=1s
      --wal-checkpoint-interval=5m
      --wal-max-size=1GB
      --wal-retention-period=1h
    environment:
      INFLUXDB_WAL_MAX_SIZE: 1GB
      INFLUXDB_WAL_CHECKPOINT_INTERVAL: 5m
      INFLUXDB_WAL_RETENTION_PERIOD: 1h
    ports:
      - "${INFLUXDB_PORT:-8087}:8181"
    volumes:
      - influxdb_data:/var/lib/influxdb3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    stop_grace_period: 30s
    stop_signal: SIGTERM
    networks:
      - waterpump-network
    restart: unless-stopped

  # Nest.js Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    container_name: waterpump-api
    environment:
      NODE_ENV: development
      PORT: 3000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      ONESIGNAL_REST_API_KEY: ${ONESIGNAL_REST_API_KEY:-}
      POSTGRES_DB: ${POSTGRES_DB:-waterpump}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      INFLUXDB_URL: http://influxdb:8181
      INFLUXDB_TOKEN: dummy-token-for-no-auth-mode
      INFLUXDB_ORG: 
      INFLUXDB_BUCKET: waterpump
    ports:
      - "${API_PORT:-3002}:3000"
    depends_on:
      - postgres
      - redis
      - influxdb
    networks:
      - waterpump-network
    restart: unless-stopped
    volumes:
      - ./src:/app/src

volumes:
  postgres_data:
  redis_data:
  influxdb_data:

networks:
  waterpump-network:
    driver: bridge