services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: waterpump-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-waterpump}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${POSTGRES_PORT:-5436}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - waterpump-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: waterpump-redis
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    networks:
      - waterpump-network
    restart: unless-stopped

  # InfluxDB 3.3 Core Time Series Database
  influxdb:
    image: influxdb:3.3-core
    container_name: waterpump-influxdb
    command: >
      influxdb3
      serve
      --node-id=node0
      --object-store=file
      --data-dir=/var/lib/influxdb3/data
      --plugin-dir=/var/lib/influxdb3/plugins
      --without-auth
      --query-file-limit=1000
      --query-memory-bytes=1073741824
      --query-concurrency-limit=4
    ports:
      - "${INFLUXDB_PORT:-8087}:8181"
    volumes:
      - influxdb_data:/var/lib/influxdb3
    networks:
      - waterpump-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Nest.js Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    container_name: waterpump-api
    environment:
      NODE_ENV: development
      PORT: 3000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_USER:-password}
      ONESIGNAL_REST_API_KEY: ${ONESIGNAL_REST_API_KEY:-}
      POSTGRES_DB: ${POSTGRES_DB:-waterpump}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      INFLUXDB_URL: http://influxdb:8181
      INFLUXDB_TOKEN: dummy-token-for-no-auth-mode
      INFLUXDB_ORG: 
      INFLUXDB_BUCKET: waterpump
      NODE_OPTIONS: "--max-old-space-size=2048 --max-semi-space-size=512"
    ports:
      - "${API_PORT:-3002}:3000"
    depends_on:
      - postgres
      - redis
      - influxdb
    networks:
      - waterpump-network
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G

volumes:
  postgres_data:
  redis_data:
  influxdb_data:

networks:
  waterpump-network:
    driver: bridge