version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: waterpump-postgres-prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-waterpump}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${POSTGRES_PORT:-5436}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - waterpump-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: waterpump-redis-prod
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    networks:
      - waterpump-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # DuckDB Data Volume (Local SQL Database)
  # Note: DuckDB runs embedded in the API container, no separate service needed

  # Nest.js Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: waterpump-api-prod
    environment:
      NODE_ENV: production
      PORT: 3000
      NODE_OPTIONS: "--max-old-space-size=4096 --optimize-for-size"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      ONESIGNAL_REST_API_KEY: ${ONESIGNAL_REST_API_KEY:-}
      POSTGRES_DB: ${POSTGRES_DB:-waterpump}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DUCKDB_PATH: /app/data/waterpump_data.duckdb
    ports:
      - "${API_PORT:-3002}:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - duckdb_data:/app/data
    networks:
      - waterpump-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  postgres_data:
  redis_data:
  duckdb_data:

networks:
  waterpump-network:
    driver: bridge 